using System.Collections;
using System.Collections.Generic;
using Photon.Pun;
using Photon.Realtime;
using UnityEngine;
using UnityEngine.AI;
using UnityEngine.SceneManagement;

public class MapGenerator : MonoBehaviourPunCallbacks//, IPunObservable
{
    bool pushFlag = false;
    public int mapStart = 0;

    public int MapWidth;
    public int MapHeight;

    int[,] Map;

    public int wall;
    public int road;

    public GameObject WallObject;

    public int roomMinHeight;
    public int roomMaxHeight;

    public int roomMinWidth;
    public int roomMaxWidth;

    public int RoomCountMin;
    public int RoomCountMax;

    public int roadWidth;

    // ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    public GameObject cube;             // ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½Ìƒï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    public GameObject kaidan;           // ï¿½ï¿½ï¿½Ìƒtï¿½ï¿½ï¿½Aï¿½ÖŠKï¿½i

    //ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[
    public GameObject Enmspawner01;
    public GameObject Enmspawner02;
    public GameObject Enmspawner03;
    public GameObject Enmspawner04;
    public GameObject Enmspawner05;
    public GameObject Enmspawner06;
    public GameObject Enmspawner07;
    public GameObject Enmspawner08;
    public GameObject Enmspawner09;
    public GameObject Enmspawner10;
    public GameObject Enmspawner11;
    public GameObject Enmspawner12;
    public GameObject Enmspawner13;
    public GameObject Enmspawner14;
    public GameObject Enmspawner15;

    [SerializeField]

    //ï¿½ï¿½ï¿½ÌWï¿½ï¿½ï¿½_ï¿½ğ‘‚â‚µï¿½ï¿½ï¿½ï¿½ï¿½È‚ç‚±ï¿½ï¿½ğ‘‚â‚·
    const int meetPointCount = 2;




    public int seedNum;     //ï¿½Vï¿½[ï¿½hï¿½l
    public int seed;
    GameObject seedObject;
    MapRandomSeed seedScript;


    

    void Update()
    {
        if (Input.GetKeyDown(KeyCode.M))
        {

            mapStart = 1;



            seedObject = GameObject.Find("seedObject");
            seedScript = seedObject.GetComponent<MapRandomSeed>();

            //seedSetting();


            //Random.InitState(seed);
            Random.InitState(seedScript.seedNum);

            ResetMapData();

            CreateSpaceData();

            CreateDangeon();

            RandomSpawn();          // ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½Ìƒï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½

            RandomSpawn2();         // ï¿½Kï¿½i

            EnmSpawner01();         // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[1
            EnmSpawner02();         // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[2
            EnmSpawner03();         // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[3
            EnmSpawner04();         // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[4
            EnmSpawner05();         // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[5
            EnmSpawner06();         // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[6
            EnmSpawner07();         // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[7
            EnmSpawner08();         // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[8
            EnmSpawner09();         // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[9
            EnmSpawner10();         // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[10
            EnmSpawner11();         // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[11
            EnmSpawner12();         // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[12
            EnmSpawner13();         // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[13
            EnmSpawner14();         // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[14
            EnmSpawner15();         // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[15

            mapStart = 0;




            print("ï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½Mï¿½ï¿½ï¿½mï¿½F");
        }

        if (Input.GetKeyDown(KeyCode.C))
        {
            PhotonNetwork.IsMessageQueueRunning = false;
            SceneManager.LoadScene("Kaihatuyou");
        }

    }
    

    void seedSetting()
    {
        seedNum = Random.Range(0, 100); //ï¿½Vï¿½[ï¿½hï¿½lï¿½ğ—ï¿½ï¿½ÅƒZï¿½bï¿½gï¿½ï¿½ï¿½ï¿½
        print("mapgeneraterï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½Zï¿½bï¿½gï¿½Ìï¿½ï¿½_ï¿½ï¿½" + seedNum);
    }

    int setSeed()
    {
        int seed = Random.Range(0, 100);

        Random.InitState(seed);
        print("seed" + seed);

        return seed;
    }

    /// <summary>
    /// Mapï¿½Ì“ñŸŒï¿½ï¿½zï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½
    /// </summary>
    private void ResetMapData()
    {
        Map = new int[MapHeight, MapWidth];
        for (int i = 0; i < MapHeight; i++)
        {
            for (int j = 0; j < MapWidth; j++)
            {
                Map[i, j] = wall;
            }
        }
    }

    /// <summary>
    /// ï¿½ó”’•ï¿½ï¿½ï¿½ï¿½Ìƒfï¿½[ï¿½^ï¿½ï¿½ÏX
    /// </summary>
    private void CreateSpaceData()
    {
        int roomCount = Random.Range(RoomCountMin, RoomCountMax);

        int[] meetPointsX = new int[meetPointCount];
        int[] meetPointsY = new int[meetPointCount];
        for (int i = 0; i < meetPointsX.Length; i++)
        {
            meetPointsX[i] = Random.Range(MapWidth / 4, MapWidth * 3 / 4);
            meetPointsY[i] = Random.Range(MapHeight / 4, MapHeight * 3 / 4);
            Map[meetPointsY[i], meetPointsX[i]] = road;
        }

        for (int i = 0; i < roomCount; i++)
        {
            int roomHeight = Random.Range(roomMinHeight, roomMaxHeight);
            int roomWidth = Random.Range(roomMinWidth, roomMaxWidth);
            int roomPointX = Random.Range(2, MapWidth - roomMaxWidth - 2);
            int roomPointY = Random.Range(2, MapWidth - roomMaxWidth - 2);

            int roadStartPointX = Random.Range(roomPointX, roomPointX + roomWidth);
            int roadStartPointY = Random.Range(roomPointY, roomPointY + roomHeight);

            bool isRoad = CreateRoomData(roomHeight, roomWidth, roomPointX, roomPointY);

            if (isRoad == false)
            {
                CreateRoadData(roadStartPointX, roadStartPointY, meetPointsX[Random.Range(0, 0)], meetPointsY[Random.Range(0, 0)]);
            }
        }
    }

    /// <summary>
    /// ï¿½ï¿½ï¿½ï¿½ï¿½fï¿½[ï¿½^ï¿½ğ¶ï¿½ï¿½Bï¿½ï¿½ï¿½Å‚É•ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‡ï¿½ï¿½trueï¿½ï¿½Ô‚ï¿½ï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½ï¿½æ‚¤ï¿½É‚ï¿½ï¿½ï¿½
    /// </summary>
    /// <param name="roomHeight">ï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½</param>
    /// <param name="roomWidth">ï¿½ï¿½ï¿½ï¿½ï¿½Ì‰ï¿½ï¿½ï¿½</param>
    /// <param name="roomPointX">ï¿½ï¿½ï¿½ï¿½ï¿½Ìnï¿½_(x)</param>
    /// <param name="roomPointY">ï¿½ï¿½ï¿½ï¿½ï¿½Ìnï¿½_(y)</param>
    /// <returns></returns>
    private bool CreateRoomData(int roomHeight, int roomWidth, int roomPointX, int roomPointY)
    {
        bool isRoad = false;
        for (int i = 0; i < roomHeight; i++)
        {
            for (int j = 0; j < roomWidth; j++)
            {
                if (Map[roomPointY + i, roomPointX + j] == road)
                {
                    isRoad = true;
                }
                else
                {
                    Map[roomPointY + i, roomPointX + j] = road;
                }
            }
        }
        return isRoad;
    }

    /// <summary>
    /// ï¿½ï¿½ï¿½fï¿½[ï¿½^ï¿½ğ¶ï¿½
    /// </summary>
    /// <param name="roadStartPointX"></param>
    /// <param name="roadStartPointY"></param>
    /// <param name="meetPointX"></param>
    /// <param name="meetPointY"></param>
    private void CreateRoadData(int roadStartPointX, int roadStartPointY, int meetPointX, int meetPointY)
    {

        bool isRight;
        if (roadStartPointX > meetPointX)
        {
            isRight = true;
        }
        else
        {
            isRight = false;
        }
        bool isUnder;
        if (roadStartPointY > meetPointY)
        {
            isUnder = false;
        }
        else
        {
            isUnder = true;
        }

        if (Random.Range(0, 2) == 0)
        {

            while (roadStartPointX != meetPointX)
            {

                for (int i = 0; i < roadWidth; i++)
                {
                    Map[roadStartPointY + i, roadStartPointX] = road;
                }
                if (isRight == true)
                {
                    roadStartPointX--;
                }
                else
                {
                    roadStartPointX++;
                }

            }

            while (roadStartPointY != meetPointY)
            {

                for (int i = 0; i < roadWidth; i++)
                {
                    Map[roadStartPointY, roadStartPointX + i] = road;
                }
                if (isUnder == true)
                {
                    roadStartPointY++;
                }
                else
                {
                    roadStartPointY--;
                }
            }

        }
        else
        {

            while (roadStartPointY != meetPointY)
            {

                for (int i = 0; i < roadWidth; i++)
                {
                    Map[roadStartPointY, roadStartPointX + i] = road;
                }
                if (isUnder == true)
                {
                    roadStartPointY++;
                }
                else
                {
                    roadStartPointY--;
                }
            }

            while (roadStartPointX != meetPointX)
            {

                for (int i = 0; i < roadWidth; i++)
                {
                    Map[roadStartPointY + i, roadStartPointX] = road;
                }
                if (isRight == true)
                {
                    roadStartPointX--;
                }
                else
                {
                    roadStartPointX++;
                }
            }
        }
    }

    /// <summary>
    /// ï¿½}ï¿½bï¿½vï¿½fï¿½[ï¿½^ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚Éƒ_ï¿½ï¿½ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½ğ¶ï¿½
    /// </summary>
    private void CreateDangeon()
    {
        for (int i = 0; i < MapHeight; i+=4)
        {
            for (int j = 0; j < MapWidth; j+=4)
            {
                if (Map[i, j] == wall)
                {
                    Instantiate(WallObject, new Vector3(j - MapWidth / 2,0 , i - MapHeight / 2), Quaternion.identity);
                }
            }
        }
        // NavMeshï¿½ï¿½ï¿½rï¿½ï¿½ï¿½hï¿½ï¿½ï¿½ï¿½
        // Debug.Log("ï¿½È‚ï¿½");
        //_surface.BuildNavMesh();ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    }

    // ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½Ìƒï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    private void RandomSpawn()
    {
        int x, y, z;
        do
        {
            x = Random.Range(0, MapWidth);
            y = Random.Range(-1, -1);
            z = Random.Range(0, MapHeight);
        }
        while (Map[z, x] != road);

        // Instantiate(cube, new Vector3(y - MapWidth / 2, x - MapHeight / 2, 0), Quaternion.identity);
        Instantiate(cube, new Vector3(x - MapWidth / 2,y, z - MapHeight/2), Quaternion.identity);

    }

    // ï¿½ï¿½ï¿½Ìƒtï¿½ï¿½ï¿½Aï¿½ÖŠKï¿½i
    private void RandomSpawn2()
    {
        int x, y, z;
        do
        {
            x = Random.Range(0, MapWidth);
            y = Random.Range(-1, -1);
            z = Random.Range(0, MapHeight);
        }
        while (Map[z, x] != road);

        // Instantiate(cube, new Vector3(y - MapWidth / 2, x - MapHeight / 2, 0), Quaternion.identity);
        Instantiate(kaidan, new Vector3(x - MapWidth / 2, y, z - MapHeight / 2), Quaternion.identity);

    }


    // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[01
    private void EnmSpawner01()
    {
        int x, y, z;
        do
        {
            x = Random.Range(0, MapWidth);
            y = Random.Range(-1, -1);
            z = Random.Range(0, MapHeight);
        }
        while (Map[z, x] != road);

        Instantiate(Enmspawner01, new Vector3(x - MapWidth / 2, y, z - MapHeight / 2), Quaternion.identity);

    }

    // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[02
    private void EnmSpawner02()
    {
        int x, y, z;
        do
        {
            x = Random.Range(0, MapWidth);
            y = Random.Range(-1, -1);
            z = Random.Range(0, MapHeight);
        }
        while (Map[z, x] != road);

        Instantiate(Enmspawner02, new Vector3(x - MapWidth / 2, y, z - MapHeight / 2), Quaternion.identity);

    }

    // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[03
    private void EnmSpawner03()
    {
        int x, y, z;
        do
        {
            x = Random.Range(0, MapWidth);
            y = Random.Range(-1, -1);
            z = Random.Range(0, MapHeight);
        }
        while (Map[z, x] != road);

        Instantiate(Enmspawner03, new Vector3(x - MapWidth / 2, y, z - MapHeight / 2), Quaternion.identity);

    }

    // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[04
    private void EnmSpawner04()
    {
        int x, y, z;
        do
        {
            x = Random.Range(0, MapWidth);
            y = Random.Range(-1, -1);
            z = Random.Range(0, MapHeight);
        }
        while (Map[z, x] != road);

        Instantiate(Enmspawner04, new Vector3(x - MapWidth / 2, y, z - MapHeight / 2), Quaternion.identity);

    }


    // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[05
    private void EnmSpawner05()
    {
        int x, y, z;
        do
        {
            x = Random.Range(0, MapWidth);
            y = Random.Range(-1, -1);
            z = Random.Range(0, MapHeight);
        }
        while (Map[z, x] != road);

        Instantiate(Enmspawner05, new Vector3(x - MapWidth / 2, y, z - MapHeight / 2), Quaternion.identity);

    }

    // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[06
    private void EnmSpawner06()
    {
        int x, y, z;
        do
        {
            x = Random.Range(0, MapWidth);
            y = Random.Range(-1, -1);
            z = Random.Range(0, MapHeight);
        }
        while (Map[z, x] != road);

        Instantiate(Enmspawner06, new Vector3(x - MapWidth / 2, y, z - MapHeight / 2), Quaternion.identity);

    }

    // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[07
    private void EnmSpawner07()
    {
        int x, y, z;
        do
        {
            x = Random.Range(0, MapWidth);
            y = Random.Range(-1, -1);
            z = Random.Range(0, MapHeight);
        }
        while (Map[z, x] != road);

        Instantiate(Enmspawner07, new Vector3(x - MapWidth / 2, y, z - MapHeight / 2), Quaternion.identity);

    }

    // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[08
    private void EnmSpawner08()
    {
        int x, y, z;
        do
        {
            x = Random.Range(0, MapWidth);
            y = Random.Range(-1, -1);
            z = Random.Range(0, MapHeight);
        }
        while (Map[z, x] != road);

        Instantiate(Enmspawner08, new Vector3(x - MapWidth / 2, y, z - MapHeight / 2), Quaternion.identity);

    }

    // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[09
    private void EnmSpawner09()
    {
        int x, y, z;
        do
        {
            x = Random.Range(0, MapWidth);
            y = Random.Range(-1, -1);
            z = Random.Range(0, MapHeight);
        }
        while (Map[z, x] != road);

        Instantiate(Enmspawner09, new Vector3(x - MapWidth / 2, y, z - MapHeight / 2), Quaternion.identity);

    }

    // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[10
    private void EnmSpawner10()
    {
        int x, y, z;
        do
        {
            x = Random.Range(0, MapWidth);
            y = Random.Range(-1, -1);
            z = Random.Range(0, MapHeight);
        }
        while (Map[z, x] != road);

        Instantiate(Enmspawner10, new Vector3(x - MapWidth / 2, y, z - MapHeight / 2), Quaternion.identity);

    }

    // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[11
    private void EnmSpawner11()
    {
        int x, y, z;
        do
        {
            x = Random.Range(0, MapWidth);
            y = Random.Range(-1, -1);
            z = Random.Range(0, MapHeight);
        }
        while (Map[z, x] != road);

        Instantiate(Enmspawner11, new Vector3(x - MapWidth / 2, y, z - MapHeight / 2), Quaternion.identity);

    }

    // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[12
    private void EnmSpawner12()
    {
        int x, y, z;
        do
        {
            x = Random.Range(0, MapWidth);
            y = Random.Range(-1, -1);
            z = Random.Range(0, MapHeight);
        }
        while (Map[z, x] != road);

        Instantiate(Enmspawner12, new Vector3(x - MapWidth / 2, y, z - MapHeight / 2), Quaternion.identity);

    }

    // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[13
    private void EnmSpawner13()
    {
        int x, y, z;
        do
        {
            x = Random.Range(0, MapWidth);
            y = Random.Range(-1, -1);
            z = Random.Range(0, MapHeight);
        }
        while (Map[z, x] != road);

        Instantiate(Enmspawner13, new Vector3(x - MapWidth / 2, y, z - MapHeight / 2), Quaternion.identity);

    }

    // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[14
    private void EnmSpawner14()
    {
        int x, y, z;
        do
        {
            x = Random.Range(0, MapWidth);
            y = Random.Range(-1, -1);
            z = Random.Range(0, MapHeight);
        }
        while (Map[z, x] != road);

        Instantiate(Enmspawner14, new Vector3(x - MapWidth / 2, y, z - MapHeight / 2), Quaternion.identity);

    }
    // ï¿½Gï¿½ÌƒXï¿½|ï¿½iï¿½[15
    private void EnmSpawner15()
    {
        int x, y, z;
        do
        {
            x = Random.Range(0, MapWidth);
            y = Random.Range(-1, -1);
            z = Random.Range(0, MapHeight);
        }
        while (Map[z, x] != road);

        Instantiate(Enmspawner15, new Vector3(x - MapWidth / 2, y, z - MapHeight / 2), Quaternion.identity);

    }
    /*
    void IPunObservable.OnPhotonSerializeView(PhotonStream stream, PhotonMessageInfo info)
    {
        if (stream.IsWriting)
        {
            stream.SendNext(seedNum);
        }
        else
        {
            seedNum = (int)stream.ReceiveNext();
        }
    }
    */
}